/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiQuoteRouteImport } from './routes/api/ai-quote'
import { Route as ApiAiAdvisorRouteImport } from './routes/api/ai-advisor'
import { Route as CategoryProductRouteImport } from './routes/$category.$product'

const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiQuoteRoute = ApiAiQuoteRouteImport.update({
  id: '/api/ai-quote',
  path: '/api/ai-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAdvisorRoute = ApiAiAdvisorRouteImport.update({
  id: '/api/ai-advisor',
  path: '/api/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryProductRoute = CategoryProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => CategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/$category/$product': typeof CategoryProductRoute
  '/api/ai-advisor': typeof ApiAiAdvisorRoute
  '/api/ai-quote': typeof ApiAiQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/$category/$product': typeof CategoryProductRoute
  '/api/ai-advisor': typeof ApiAiAdvisorRoute
  '/api/ai-quote': typeof ApiAiQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/$category/$product': typeof CategoryProductRoute
  '/api/ai-advisor': typeof ApiAiAdvisorRoute
  '/api/ai-quote': typeof ApiAiQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/$category/$product'
    | '/api/ai-advisor'
    | '/api/ai-quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/$category/$product'
    | '/api/ai-advisor'
    | '/api/ai-quote'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/$category/$product'
    | '/api/ai-advisor'
    | '/api/ai-quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  ApiAiAdvisorRoute: typeof ApiAiAdvisorRoute
  ApiAiQuoteRoute: typeof ApiAiQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-quote': {
      id: '/api/ai-quote'
      path: '/api/ai-quote'
      fullPath: '/api/ai-quote'
      preLoaderRoute: typeof ApiAiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-advisor': {
      id: '/api/ai-advisor'
      path: '/api/ai-advisor'
      fullPath: '/api/ai-advisor'
      preLoaderRoute: typeof ApiAiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$product': {
      id: '/$category/$product'
      path: '/$product'
      fullPath: '/$category/$product'
      preLoaderRoute: typeof CategoryProductRouteImport
      parentRoute: typeof CategoryRoute
    }
  }
}

interface CategoryRouteChildren {
  CategoryProductRoute: typeof CategoryProductRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryProductRoute: CategoryProductRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  ApiAiAdvisorRoute: ApiAiAdvisorRoute,
  ApiAiQuoteRoute: ApiAiQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
